UD4-Modelo-Vista-Controlador (MVC)/Ejercicios/Ejercicio4/Ejercicio1/Models/Producto.cs
using System.ComponentModel.DataAnnotations;

namespace Ejercicio1.Models
{
    public class Producto
    {
        [Key]
        public int codigo { get; set; }
        public string nombre { get; set; }
        public double precio { get; set; }
        public int codigo_fabricante { get; set; }
    }
}

UD4-Modelo-Vista-Controlador (MVC)/Ejercicios/Ejercicio4/Ejercicio1/Models/ProductoContext.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Hosting;
using System.Collections.Generic;

namespace Ejercicio1.Models
{
    public class ProductoContext : DbContext
    {
        public ProductoContext(DbContextOptions<ProductoContext> options) : base(options)
        { }
        public DbSet<Producto> Producto { get; set; }
    }
}

UD4-Modelo-Vista-Controlador (MVC)/Ejercicios/Ejercicio4/Ejercicio1/Controllers/ProductoController.cs
using Ejercicio1.Models;
using Microsoft.AspNetCore.Mvc;
using System.Xml.Linq;

namespace Ejercicio1.Controllers
{
    public class ProductoController : Controller
    {
        private readonly ProductoContext _contexto;

        public ProductoController(ProductoContext contexto)
        {
            _contexto = contexto;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult VerProducto(int codigo)
        {
            List<Producto> listaProductos = new List<Producto>();

            listaProductos.Add(_contexto.Producto.FirstOrDefault(producto => producto.codigo == codigo));

            return View("ListaProductos", listaProductos);
        }

        [HttpGet]
        public IActionResult BorrarProducto(int codigo)
        {
            _contexto.Producto.Remove(_contexto.Producto.FirstOrDefault(producto => producto.codigo == codigo));

            _contexto.SaveChanges();

            return View("Index");
        }
    }
}

UD4-Modelo-Vista-Controlador (MVC)/Ejercicios/Ejercicio4/Ejercicio1/Views/Producto/Index.cshtml
@model IEnumerable<Ejercicio1.Models.Producto>

@{
    ViewData["Title"] = "Consulta de producto";
}

<h1>Consulta de producto</h1>

@using(Html.BeginForm("VerProducto","Producto",FormMethod.Post))
{
    <div class="form-group">
        <label for="codigo">Codigo</label>
        <input type="text" class="form-control" name="codigo" id="codigo">
    </div>

    <button type="submit" class="btn btn-primary">Consultar</button>
}

UD4-Modelo-Vista-Controlador (MVC)/Ejercicios/Ejercicio4/Ejercicio1/Views/Producto/ListaProductos.cshtml
@model IEnumerable<Ejercicio1.Models.Producto>

@{
    ViewData["Title"] = "Lista de productos";
}

<h1>Lista de productos</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.codigo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.precio)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.codigo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.precio)
            </td>
            <td>
                @Html.ActionLink("Borrar",
                    "BorrarProducto",
                    "Producto",
                    new { codigo = item.codigo },
                    null
                )
            </td>
        </tr>
}
    </tbody>
</table>